version: "3.9"
services:
  db:
    image: postgres:14.1

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
  web:
    container_name: drf_ls
    build: .
    ports:
      - ${PORT}
    command: python manage.py runserver ${HOSTNAME}:8000
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    depends_on:
      - db
volumes:
  postgres_data:
